server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/account/**
        - id: test-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/test/**, /api/v1/answer/**, /api/v1/resource/**, /api/v1/question/**
        - id: attempt-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/v1/attempt/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
